import type { Trail } from '@/types';

export const MOCK_TRAILS: Omit<Trail, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    name: 'Sentier Scout — Mafate par le Col des Boeufs',
    slug: 'mafate-col-des-boeufs',
    description:
      "L'acces le plus classique au cirque de Mafate via le Col des Boeufs. Descente vers La Nouvelle a travers la foret de cryptomerias.",
    difficulty: 'moyen',
    distance_km: 11.5,
    elevation_gain_m: 850,
    duration_min: 300,
    trail_type: 'aller-retour',
    region: 'Cirque de Mafate',
    start_point: { latitude: -21.0695, longitude: 55.453 },
    end_point: { latitude: -21.058, longitude: 55.428 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Ilet des Orangers par Riviere des Galets',
    slug: 'mafate-ilet-des-orangers',
    description:
      "Remontee spectaculaire de la Riviere des Galets jusqu'a l'Ilet des Orangers, au coeur de Mafate.",
    difficulty: 'difficile',
    distance_km: 16.0,
    elevation_gain_m: 1200,
    duration_min: 420,
    trail_type: 'aller-retour',
    region: 'Cirque de Mafate',
    start_point: { latitude: -21.003, longitude: 55.315 },
    end_point: { latitude: -21.045, longitude: 55.41 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Roche Plate — Maido a Mafate',
    slug: 'mafate-roche-plate-maido',
    description:
      'Descente vertigineuse depuis le Maido vers Roche Plate dans le cirque de Mafate. Sentier aerien avec vues exceptionnelles.',
    difficulty: 'expert',
    distance_km: 14.0,
    elevation_gain_m: 1500,
    duration_min: 480,
    trail_type: 'aller-retour',
    region: 'Cirque de Mafate',
    start_point: { latitude: -21.068, longitude: 55.384 },
    end_point: { latitude: -21.055, longitude: 55.405 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Piton des Neiges par Cilaos',
    slug: 'cilaos-piton-des-neiges',
    description:
      "Ascension du point culminant de l'ocean Indien (3070m) depuis le bloc a Cilaos. Nuit au gite de la Caverne Dufour recommandee.",
    difficulty: 'difficile',
    distance_km: 15.0,
    elevation_gain_m: 1750,
    duration_min: 540,
    trail_type: 'aller-retour',
    region: 'Cirque de Cilaos',
    start_point: { latitude: -21.129, longitude: 55.471 },
    end_point: { latitude: -21.096, longitude: 55.478 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Bras Rouge — Cilaos',
    slug: 'cilaos-bras-rouge',
    description:
      'Randonnee dans le canyon de Bras Rouge, avec ses cascades et sa vegetation luxuriante. Baignade possible.',
    difficulty: 'moyen',
    distance_km: 8.0,
    elevation_gain_m: 450,
    duration_min: 180,
    trail_type: 'boucle',
    region: 'Cirque de Cilaos',
    start_point: { latitude: -21.135, longitude: 55.468 },
    end_point: null,
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Roche Merveilleuse',
    slug: 'cilaos-roche-merveilleuse',
    description:
      'Court sentier menant au belvedere de la Roche Merveilleuse, panorama exceptionnel sur tout le cirque de Cilaos.',
    difficulty: 'facile',
    distance_km: 3.5,
    elevation_gain_m: 200,
    duration_min: 75,
    trail_type: 'aller-retour',
    region: 'Cirque de Cilaos',
    start_point: { latitude: -21.126, longitude: 55.47 },
    end_point: { latitude: -21.12, longitude: 55.465 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Trou de Fer — Belouve',
    slug: 'salazie-trou-de-fer',
    description:
      "Traversee de la foret primaire de Belouve jusqu'au belvedere du Trou de Fer, l'un des canyons les plus profonds au monde.",
    difficulty: 'moyen',
    distance_km: 10.0,
    elevation_gain_m: 350,
    duration_min: 210,
    trail_type: 'aller-retour',
    region: 'Cirque de Salazie',
    start_point: { latitude: -21.063, longitude: 55.53 },
    end_point: { latitude: -21.058, longitude: 55.51 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Cascade du Voile de la Mariee',
    slug: 'salazie-voile-de-la-mariee',
    description:
      'Balade facile vers la celebre cascade du Voile de la Mariee, embleme du cirque de Salazie.',
    difficulty: 'facile',
    distance_km: 2.0,
    elevation_gain_m: 100,
    duration_min: 45,
    trail_type: 'aller-retour',
    region: 'Cirque de Salazie',
    start_point: { latitude: -21.043, longitude: 55.511 },
    end_point: { latitude: -21.04, longitude: 55.508 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Enclos Fouque — Cratere Dolomieu',
    slug: 'volcan-enclos-fouque-dolomieu',
    description:
      'La randonnee mythique du Piton de la Fournaise : traversee de la Plaine des Sables, descente dans l\'Enclos, montee au sommet du Dolomieu.',
    difficulty: 'moyen',
    distance_km: 12.0,
    elevation_gain_m: 530,
    duration_min: 300,
    trail_type: 'aller-retour',
    region: 'Massif du Volcan',
    start_point: { latitude: -21.224, longitude: 55.683 },
    end_point: { latitude: -21.244, longitude: 55.71 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Piton de Bert',
    slug: 'volcan-piton-de-bert',
    description:
      "Point de vue spectaculaire sur l'Enclos Fouque et le Piton de la Fournaise. Accessible depuis le Pas de Bellecombe.",
    difficulty: 'facile',
    distance_km: 5.0,
    elevation_gain_m: 250,
    duration_min: 120,
    trail_type: 'boucle',
    region: 'Massif du Volcan',
    start_point: { latitude: -21.224, longitude: 55.683 },
    end_point: null,
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Plaine des Sables',
    slug: 'volcan-plaine-des-sables',
    description:
      'Traversee lunaire de la Plaine des Sables, paysage unique au monde rappelant Mars. Panorama a 360 sur le massif volcanique.',
    difficulty: 'moyen',
    distance_km: 8.5,
    elevation_gain_m: 300,
    duration_min: 180,
    trail_type: 'point-a-point',
    region: 'Massif du Volcan',
    start_point: { latitude: -21.21, longitude: 55.65 },
    end_point: { latitude: -21.224, longitude: 55.683 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: "Piton de l'Eau",
    slug: 'plaine-des-cafres-piton-de-leau',
    description:
      "Randonnee vers le lac volcanique du Piton de l'Eau a travers les prairies et forets des Hauts. Ambiance montagnarde.",
    difficulty: 'facile',
    distance_km: 7.0,
    elevation_gain_m: 200,
    duration_min: 150,
    trail_type: 'aller-retour',
    region: 'Plaine des Cafres',
    start_point: { latitude: -21.185, longitude: 55.589 },
    end_point: { latitude: -21.178, longitude: 55.575 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Foret de Bebour — Sentier botanique',
    slug: 'bebour-sentier-botanique',
    description:
      'Sentier amenage au coeur de la foret primaire de Bebour. Fougeres arborescentes geantes, tamarins des hauts.',
    difficulty: 'facile',
    distance_km: 4.0,
    elevation_gain_m: 150,
    duration_min: 90,
    trail_type: 'boucle',
    region: 'Foret de Bebour-Belouve',
    start_point: { latitude: -21.09, longitude: 55.545 },
    end_point: null,
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: "Cap Noir — Dos d'Ane",
    slug: 'ouest-cap-noir-dos-dane',
    description:
      'Belvedere de Cap Noir offrant une vue plongeante sur le cirque de Mafate. Court mais spectaculaire.',
    difficulty: 'facile',
    distance_km: 3.0,
    elevation_gain_m: 150,
    duration_min: 60,
    trail_type: 'aller-retour',
    region: 'Cote Ouest',
    start_point: { latitude: -21.019, longitude: 55.395 },
    end_point: { latitude: -21.023, longitude: 55.398 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Anse des Cascades',
    slug: 'sud-sauvage-anse-des-cascades',
    description:
      "Promenade littorale le long des falaises du Sud Sauvage jusqu'a l'Anse des Cascades.",
    difficulty: 'facile',
    distance_km: 4.5,
    elevation_gain_m: 80,
    duration_min: 75,
    trail_type: 'boucle',
    region: 'Grand Sud Sauvage',
    start_point: { latitude: -21.18, longitude: 55.78 },
    end_point: null,
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Pointe de la Table — Coulee de 2007',
    slug: 'sud-sauvage-pointe-de-la-table',
    description:
      "Marche sur la coulee de lave de 2007 qui a agrandi l'ile. Paysage mineral brut, vegetation pionniere.",
    difficulty: 'moyen',
    distance_km: 6.0,
    elevation_gain_m: 150,
    duration_min: 120,
    trail_type: 'aller-retour',
    region: 'Grand Sud Sauvage',
    start_point: { latitude: -21.205, longitude: 55.775 },
    end_point: { latitude: -21.21, longitude: 55.79 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Takamaka — Bras Cabot',
    slug: 'nord-est-takamaka',
    description:
      "Descente vers le site hydroelectrique de Takamaka, au fond d'une vallee encaissee spectaculaire. Cascades monumentales.",
    difficulty: 'difficile',
    distance_km: 10.0,
    elevation_gain_m: 900,
    duration_min: 300,
    trail_type: 'aller-retour',
    region: 'Hauts du Nord-Est',
    start_point: { latitude: -21.05, longitude: 55.595 },
    end_point: { latitude: -21.06, longitude: 55.58 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Grand Benare par le Maido',
    slug: 'grand-benare-maido',
    description:
      "Randonnee d'altitude sur la crete entre le Maido et le Grand Benare (2898m). Vue simultanee sur Mafate et la cote Ouest.",
    difficulty: 'difficile',
    distance_km: 16.0,
    elevation_gain_m: 1100,
    duration_min: 420,
    trail_type: 'aller-retour',
    region: 'Grand Benare',
    start_point: { latitude: -21.068, longitude: 55.384 },
    end_point: { latitude: -21.105, longitude: 55.41 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
  {
    name: 'Riviere des Remparts — Nez de Boeuf',
    slug: 'riviere-des-remparts-nez-de-boeuf',
    description:
      'Descente dans la vallee encaissee de la Riviere des Remparts depuis le belvedere du Nez de Boeuf. Paysage grandiose.',
    difficulty: 'difficile',
    distance_km: 14.0,
    elevation_gain_m: 1300,
    duration_min: 420,
    trail_type: 'aller-retour',
    region: 'Riviere des Remparts',
    start_point: { latitude: -21.195, longitude: 55.61 },
    end_point: { latitude: -21.21, longitude: 55.63 },
    gpx_url: null,
    tiles_url: null,
    tiles_size_mb: null,
    omf_trail_id: null,
  },
];
